project:
  type: website
  output-dir: docs

website:
  title: 'Practice in Code'
  site-url: https://tlint101.github.io/practice-in-code/
  description: 'Practice in Code'
  page-footer: 'Website made with [Quarto](https://quarto.org/) by Tony E. LinÂ© 2023 - 2024'
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/tlint101/practice-in-code/
      - icon: rss
        href: index.xml
  google-analytics: "G-DKY2WMQ374"
format:
  html:
    theme:
      light: [flatly, css/light.css]
      dark: [darkly, css/dark.css]

comments:
  utterances:
    repo: https://github.com/tlint101/practice-in-code/tree/main

execute:
  freeze: auto
  